/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatNotionLuizaRouteImport } from './routes/_chat.notion-luiza'
import { Route as ChatNotionRaphaDaviRouteImport } from './routes/_chat.notion-rapha-davi'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatNotionLuizaRoute = ChatNotionLuizaRouteImport.update({
  id: '/notion-luiza',
  path: '/notion-luiza',
  getParentRoute: () => ChatRoute,
} as any)
const ChatNotionRaphaDaviRoute = ChatNotionRaphaDaviRouteImport.update({
  id: '/notion-rapha-davi',
  path: '/notion-rapha-davi',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRoute
  '/notion-luiza': typeof ChatNotionLuizaRoute
  '/notion-rapha-davi': typeof ChatNotionRaphaDaviRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/settings': typeof ChatSettingsRoute
  '/notion-luiza': typeof ChatNotionLuizaRoute
  '/notion-rapha-davi': typeof ChatNotionRaphaDaviRoute
  '/': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/notion-luiza': typeof ChatNotionLuizaRoute
  '/_chat/notion-rapha-davi': typeof ChatNotionRaphaDaviRoute
  '/_chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$threadId' | '/settings' | '/notion-luiza' | '/notion-rapha-davi'
  fileRoutesByTo: FileRoutesByTo
  to: '/$threadId' | '/settings' | '/notion-luiza' | '/notion-rapha-davi' | '/'
  id: '__root__' | '/_chat' | '/_chat/$threadId' | '/_chat/settings' | '/_chat/notion-luiza' | '/_chat/notion-rapha-davi' | '/_chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/notion-luiza': {
      id: '/_chat/notion-luiza'
      path: '/notion-luiza'
      fullPath: '/notion-luiza'
      preLoaderRoute: typeof ChatNotionLuizaRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/notion-rapha-davi': {
      id: '/_chat/notion-rapha-davi'
      path: '/notion-rapha-davi'
      fullPath: '/notion-rapha-davi'
      preLoaderRoute: typeof ChatNotionRaphaDaviRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatNotionLuizaRoute: typeof ChatNotionLuizaRoute
  ChatNotionRaphaDaviRoute: typeof ChatNotionRaphaDaviRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatNotionLuizaRoute: ChatNotionLuizaRoute,
  ChatNotionRaphaDaviRoute: ChatNotionRaphaDaviRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
